Update readme with links to quickstart repositories
couchbase-examples/ottomanjs-quickstart pull request #112
Opened 2024-04-15 22:14 UTC by teetangh

2024-04-17 16:46 UTC, nithishr requested changes

2024-04-17 16:46 UTC, nithishr commented on readme.md
> +If you are looking for a quickstart using NextJs, you can find it in this [repo](https://github.com/couchbase-examples/nextjs-capella-quickstart.git)
Please update on other PRs as well

2024-05-02 23:43 UTC, teetangh commented on readme.md
> +If you are looking for a quickstart using NextJs, you can find it in this [repo](https://github.com/couchbase-examples/nextjs-capella-quickstart.git)
updated all the PRs with this naming convetion.

2024-05-07 07:58 UTC, nithishr approved these changes

2024-05-10 08:06 UTC, nithishr approved these changes

2024-05-10 10:07 UTC, merged